// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is generated by scripts/generate-sections.js
// Run 'npm run generate-sections' to regenerate

import { section as section01 } from '@/content/sections/01-welcome';
import { section as section02 } from '@/content/sections/02-what-is-microproduct';
import { section as section03 } from '@/content/sections/03-how-it-works';
import { section as section04 } from '@/content/sections/04-get-started';

export const sections = [section01, section02, section03, section04];
